/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
import java.sql.*;//should import the sql package
import javax.swing.*; //to import methods of JOptionPane 
import javax.swing.table.DefaultTableModel;
public class Doctor extends javax.swing.JFrame {

    /**
     * Creates new form Doctor
     */
    public Doctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jppatient = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnaddpatient = new javax.swing.JButton();
        txtpatientid = new javax.swing.JTextField();
        txtpatientname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbgender = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtdob = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtmajordisease = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtother = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnshowpatients = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JButton();
        btnpatientdelete = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        btnupdate = new javax.swing.JButton();
        jpaddmedicine = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtpatientmed = new javax.swing.JTextField();
        txtpatient = new javax.swing.JTextField();
        btnaddmedicine = new javax.swing.JButton();
        btnprescribe = new javax.swing.JButton();
        cmbmeal = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cbmorning = new javax.swing.JCheckBox();
        cbafternoon = new javax.swing.JCheckBox();
        cbnight = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        txtquantity = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnshowprescription = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btndelete = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jpdochome = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doctor");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("HOME");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("PATIENTS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel18.setText("MEDICINE");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel18)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnlogout.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnlogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Desktop\\java project\\logout-icon.png")); // NOI18N
        btnlogout.setText("LOGOUT");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnlogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(btnlogout)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jppatient.setBackground(new java.awt.Color(255, 204, 255));
        jppatient.setToolTipText("");

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setText("Patients");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Patient ID : ");

        btnaddpatient.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnaddpatient.setText("Add");
        btnaddpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddpatientActionPerformed(evt);
            }
        });

        txtpatientid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpatientid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpatientidActionPerformed(evt);
            }
        });
        txtpatientid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpatientidKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpatientidKeyTyped(evt);
            }
        });

        txtpatientname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpatientname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpatientnameActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Patient Name :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Gender : ");

        cmbgender.setBackground(new java.awt.Color(255, 204, 255));
        cmbgender.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cmbgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbgenderActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Major Diseases :");

        txtdob.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtdob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdobMouseClicked(evt);
            }
        });
        txtdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdobActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Date of birth :");

        txtmajordisease.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtmajordisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmajordiseaseActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Other :");

        txtother.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtaddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Address :");

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Patient Name", "Date of birth", "Address", "Gender", "Major diseases", "Other"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnshowpatients.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnshowpatients.setText("Show current patients");
        btnshowpatients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnshowpatientsMouseClicked(evt);
            }
        });

        jLabel16.setText("DD/MM/YYYY");

        btnrefresh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnrefresh.setText("Refresh");
        btnrefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrefreshMouseClicked(evt);
            }
        });
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });

        btnpatientdelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnpatientdelete.setText("Delete");
        btnpatientdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatientdeleteActionPerformed(evt);
            }
        });

        jLabel23.setText("5 digits");

        btnupdate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jppatientLayout = new javax.swing.GroupLayout(jppatient);
        jppatient.setLayout(jppatientLayout);
        jppatientLayout.setHorizontalGroup(
            jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jppatientLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jppatientLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jppatientLayout.createSequentialGroup()
                        .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jppatientLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(67, 67, 67)
                                .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jppatientLayout.createSequentialGroup()
                                .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtmajordisease, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                    .addComponent(txtother)))
                            .addGroup(jppatientLayout.createSequentialGroup()
                                .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)
                                .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtpatientid, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jppatientLayout.createSequentialGroup()
                                        .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbgender, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtpatientname, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jppatientLayout.createSequentialGroup()
                                .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnaddpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnshowpatients, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                    .addComponent(btnrefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                    .addComponent(btnpatientdelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnupdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(25, 25, 25))))
        );
        jppatientLayout.setVerticalGroup(
            jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jppatientLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpatientid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtpatientname, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jppatientLayout.createSequentialGroup()
                        .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbgender, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addGap(21, 21, 21))
                    .addGroup(jppatientLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jppatientLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmajordisease, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtother, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(17, 17, 17))
                    .addGroup(jppatientLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnaddpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jppatientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jppatientLayout.createSequentialGroup()
                        .addComponent(btnshowpatients, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnpatientdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );

        jpaddmedicine.setBackground(new java.awt.Color(0, 153, 153));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setText("Medicine");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Medicine :");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Patient ID :");

        txtpatientmed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtpatient.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpatientActionPerformed(evt);
            }
        });

        btnaddmedicine.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnaddmedicine.setText("Medicine");
        btnaddmedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddmedicineMouseClicked(evt);
            }
        });
        btnaddmedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddmedicineActionPerformed(evt);
            }
        });

        btnprescribe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnprescribe.setText("Prescribe");
        btnprescribe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnprescribeMouseClicked(evt);
            }
        });
        btnprescribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprescribeActionPerformed(evt);
            }
        });

        cmbmeal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbmeal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Before", "After" }));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Meal");

        cbmorning.setBackground(new java.awt.Color(153, 204, 0));
        cbmorning.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbmorning.setText("Morning");

        cbafternoon.setBackground(new java.awt.Color(153, 204, 0));
        cbafternoon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbafternoon.setText("Afternoon");
        cbafternoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbafternoonActionPerformed(evt);
            }
        });

        cbnight.setBackground(new java.awt.Color(102, 204, 0));
        cbnight.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbnight.setText("Night");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Quantity");

        txtquantity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Id", "Medicine Id", "Meal", "Quantity", "Morning", "Afternoon", "Evening"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnshowprescription.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnshowprescription.setText("Show prescription");
        btnshowprescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnshowprescriptionMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Check medicine / Add new medicine");

        btndelete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnclear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnclearMouseClicked(evt);
            }
        });
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaddmedicineLayout = new javax.swing.GroupLayout(jpaddmedicine);
        jpaddmedicine.setLayout(jpaddmedicineLayout);
        jpaddmedicineLayout.setHorizontalGroup(
            jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaddmedicineLayout.createSequentialGroup()
                .addGroup(jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaddmedicineLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpaddmedicineLayout.createSequentialGroup()
                                .addGroup(jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtpatientmed, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(txtpatient))
                                .addGap(45, 45, 45)
                                .addGroup(jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbmeal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addComponent(cbmorning)
                                .addGap(29, 29, 29)
                                .addComponent(cbafternoon)
                                .addGap(30, 30, 30)
                                .addComponent(cbnight))
                            .addGroup(jpaddmedicineLayout.createSequentialGroup()
                                .addGroup(jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jpaddmedicineLayout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnaddmedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btndelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnprescribe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnshowprescription, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(btnclear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jpaddmedicineLayout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel13)))
                .addGap(42, 42, 42))
        );
        jpaddmedicineLayout.setVerticalGroup(
            jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaddmedicineLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel13)
                .addGap(39, 39, 39)
                .addGroup(jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(25, 25, 25)
                .addGroup(jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbmeal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtpatientmed, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(txtquantity, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                    .addGroup(jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbafternoon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbnight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbmorning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(41, 41, 41)
                .addGroup(jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaddmedicineLayout.createSequentialGroup()
                        .addComponent(btnprescribe, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnshowprescription, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jpaddmedicineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnaddmedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        jpdochome.setBackground(new java.awt.Color(204, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Desktop\\java project\\OIP.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("DOCTOR INFORMATION");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Doctor Name :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel21.setText("Dr. A.P.Jayalath");

        javax.swing.GroupLayout jpdochomeLayout = new javax.swing.GroupLayout(jpdochome);
        jpdochome.setLayout(jpdochomeLayout);
        jpdochomeLayout.setHorizontalGroup(
            jpdochomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpdochomeLayout.createSequentialGroup()
                .addGroup(jpdochomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpdochomeLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel3))
                    .addGroup(jpdochomeLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel4)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpdochomeLayout.setVerticalGroup(
            jpdochomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpdochomeLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(75, 75, 75)
                .addGroup(jpdochomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpdochome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jppatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpaddmedicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpdochome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jppatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpaddmedicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        jpdochome.setVisible(true);         // to go from one panel to the other
        jppatient.setVisible(false);
        jpaddmedicine.setVisible(false);
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        jppatient.setVisible(true);
        jpdochome.setVisible(false);
        jpaddmedicine.setVisible(false);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void btnaddpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddpatientActionPerformed
        // TODO add your handling code here:
        String patient_id,patient_name,birth_date,gender,address,major_disease,other;
        int count=0;
        patient_id=txtpatientid.getText();      // gets the text entered to the textfields to variables
        patient_name=txtpatientname.getText();
        birth_date=txtdob.getText();
        gender=cmbgender.getSelectedItem().toString();
        address=txtaddress.getText();
        major_disease=txtmajordisease.getText();
        other=txtother.getText();
        
        int length=patient_id.length();         //patient id should be a 5 digit number
        boolean record=false, record2=false;
        if(length==5){
            for(int i=0;i<length;i++){
                if(patient_id.charAt(i)>='0' && patient_id.charAt(i)<='9'){
                    record=true;
                }else{
                    record=false;
                }
                    
            }
        }
        for(int i=0;i<patient_name.length();i++){           //Validation
            if(patient_name.matches("[a-zA-Z]+")){
                record2=true;
            }else if(i!=0 && patient_name.charAt(i)=='.'){
                record2=true;
            }
        }
        
        try{
            MyDbConnection mycon=new MyDbConnection();
            Statement st=mycon.getMyConnection().createStatement();
            
            if(txtpatientid.getText().isEmpty() || txtpatientname.getText().isEmpty() || txtdob.getText().isEmpty() || txtaddress.getText().isEmpty()){     //validation
                JOptionPane.showMessageDialog(this,"Insert required data");
            }else{
                if(record){
                    if(record2){            //insert the record into patient table once all validations done
                        count=st.executeUpdate("insert into patient values('"+patient_id+"','"+patient_name+"','"+birth_date+"','"+address+"','"+gender+"','"+major_disease+"','"+other+"')");
                    }else{
                        JOptionPane.showMessageDialog(this,"Insert only letters");
                    }
                }else{
                        JOptionPane.showMessageDialog(this,"Insert a valid patient id");
                }
            }
            if(count>0){
                    JOptionPane.showMessageDialog(this,"Record is submitted");
                    txtpatientid.setText("");txtpatientname.setText("");txtdob.setText("");txtaddress.setText("");txtmajordisease.setText("");txtother.setText(""); 
                }
                       
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnaddpatientActionPerformed

    private void txtpatientnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpatientnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpatientnameActionPerformed

    private void cmbgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbgenderActionPerformed

    private void txtpatientidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpatientidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpatientidActionPerformed

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        jpaddmedicine.setVisible(true);
        jppatient.setVisible(false);
        jpdochome.setVisible(false);
    }//GEN-LAST:event_jPanel5MouseClicked

    private void btnprescribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprescribeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnprescribeActionPerformed

    private void btnaddmedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddmedicineActionPerformed
        // TODO add your handling code here:
        Medicine med=new Medicine();        
        med.setVisible(true);
    }//GEN-LAST:event_btnaddmedicineActionPerformed

    private void btnshowpatientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnshowpatientsMouseClicked
        // TODO add your handling code here:
        try{
            MyDbConnection mycon=new MyDbConnection();
            Statement st=mycon.getMyConnection().createStatement();
            ResultSet rst=st.executeQuery("Select * from patient"); //if data available in patient table rst will be filled
            while(rst.next()) 
            {
                String pid=rst.getString("pid");
                String pname=rst.getString("pname");
                String pdob=rst.getString("pDOB");
                String paddress=rst.getString("address");
                String pgender=rst.getString("gender");
                String pmajordisease=rst.getString("major_disease");
                String pother=rst.getString("other");
                
                String patient_data[]={pid,pname,pdob,paddress,pgender,pmajordisease,pother};
                DefaultTableModel patient_table=(DefaultTableModel)jTable1.getModel();
                patient_table.addRow(patient_data);
                
            }
                    }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnshowpatientsMouseClicked

    private void cbafternoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbafternoonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbafternoonActionPerformed

    private void btnaddmedicineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddmedicineMouseClicked

    }//GEN-LAST:event_btnaddmedicineMouseClicked

    private void btnprescribeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnprescribeMouseClicked
    // TODO add your handling code here:
        String patient_id, medicine_id, meal, quantity;
        String morning="No", afternoon="No", night="No";
        int count=0;
        
        patient_id=txtpatient.getText();
        medicine_id=txtpatientmed.getText();
        meal=cmbmeal.getSelectedItem().toString();
        quantity=txtquantity.getText();
        if(cbmorning.isSelected())
            morning="Yes";
        if(cbafternoon.isSelected())
            afternoon="Yes";
        if(cbnight.isSelected())
            night="Yes";
        
        try{
            MyDbConnection mycon=new MyDbConnection();
            Statement st=mycon.getMyConnection().createStatement();
            if(patient_id.isEmpty() || medicine_id.isEmpty() || quantity.isEmpty() || meal.isEmpty() || (morning=="No"&&afternoon=="No"&&night=="No")){
                JOptionPane.showMessageDialog(this, "Insert required data");
            }else{    
                ResultSet rst=st.executeQuery("Select * from patient where pid='"+patient_id+"'");
                if(rst.next()){
                    ResultSet rst2=st.executeQuery("Select * from medicine where mid='"+medicine_id+"'");
                    if(rst2.next()){
                        count=st.executeUpdate("insert into patientmedicine values('"+patient_id+"','"+medicine_id+"','"+meal+"','"+quantity+"','"+morning+"','"+afternoon+"','"+night+"')");
                        if(count>0)
                            JOptionPane.showMessageDialog(this,"Record is submitted");
                            txtpatientmed.setText("");txtquantity.setText("");cbmorning.setSelected(false);cbafternoon.setSelected(false);cbnight.setSelected(false);
                        }
                    else{
                        JOptionPane.showMessageDialog(this, "Medicine Id is incorrect");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Patient Id is incorrect");
                }
            }
                   
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnprescribeMouseClicked

    private void btnshowprescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnshowprescriptionMouseClicked
        // TODO add your handling code here:
        String patient_id=txtpatient.getText();
        if(patient_id.isEmpty()){
            JOptionPane.showMessageDialog(this,"Enter a patient id");
        }
        try{
            MyDbConnection mycon=new MyDbConnection();
            Statement st=mycon.getMyConnection().createStatement();
            ResultSet rst=st.executeQuery("Select * from patientmedicine where pid='"+patient_id+"'");
            while(rst.next()){
                String pid=rst.getString("pid");
                String mid=rst.getString("mid");
                String meal=rst.getString("meal");
                String quantity=rst.getString("quantity");
                String morning=rst.getString("morning");
                String afternoon=rst.getString("afternoon");
                String night=rst.getString("night");
                
                String patient__medicine_data[]={pid,mid,meal,quantity,morning,afternoon,night};
                DefaultTableModel patient_medicine_table=(DefaultTableModel)jTable2.getModel();
                patient_medicine_table.addRow(patient__medicine_data);
                                
            }
            
            
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
       
        
    }//GEN-LAST:event_btnshowprescriptionMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jpdochome.setVisible(true);
        jppatient.setVisible(false);
        jpaddmedicine.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void txtpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpatientActionPerformed

    private void txtdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdobActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtdobActionPerformed

    private void txtdobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdobMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtdobMouseClicked

    private void txtmajordiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmajordiseaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmajordiseaseActionPerformed

    private void txtpatientidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpatientidKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtpatientidKeyPressed

    private void txtpatientidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpatientidKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpatientidKeyTyped

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel patient_medicine_table=(DefaultTableModel)jTable2.getModel();
        int row=jTable2.getSelectedRow();
        String cell1=jTable2.getValueAt(row,0).toString();
        String cell2=jTable2.getValueAt(row,1).toString();
        try{
            MyDbConnection mycon=new MyDbConnection();
            Statement st=mycon.getMyConnection().createStatement();
            if(jTable2.getSelectedRowCount()==1){
                st.executeUpdate("Delete from patientmedicine where pid='"+cell1+"' and mid='"+cell2+"' ");
                JOptionPane.showMessageDialog(this,"Delete successful");
                patient_medicine_table.removeRow(row);
            }else{
                JOptionPane.showMessageDialog(this,"Select one row only");
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnclearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearMouseClicked

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel patient_medicine_table=(DefaultTableModel)jTable2.getModel();
        int row_count=jTable2.getRowCount();
        System.out.println(row_count);
        for(int i=row_count-1;i>=0;i--){
           patient_medicine_table.removeRow(i); 
        }
        
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnrefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefreshMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnrefreshMouseClicked

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
        DefaultTableModel patient_table=(DefaultTableModel)jTable1.getModel();
        int row_count=jTable1.getRowCount();
        System.out.println(row_count);
        for(int i=row_count-1;i>=0;i--){
           patient_table.removeRow(i); 
        }
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnpatientdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatientdeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel patient_table=(DefaultTableModel)jTable1.getModel();
        int row=jTable1.getSelectedRow();
        String cell1=jTable1.getValueAt(row,0).toString();
        
        try{
            MyDbConnection mycon=new MyDbConnection();
            Statement st=mycon.getMyConnection().createStatement();
            if(jTable1.getSelectedRowCount()==1){
                st.executeUpdate("Delete from patient where pid='"+cell1+"'");
                JOptionPane.showMessageDialog(this,"Delete successful");
                patient_table.removeRow(row);
            }else{
                JOptionPane.showMessageDialog(this,"Select one row only");
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnpatientdeleteActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login l=new Login();
        l.setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel patient_table=(DefaultTableModel)jTable1.getModel();
        int row=jTable1.getSelectedRow();
        if(row>=0){
            patient_table.setValueAt(txtpatientid.getText(),row,0);
            patient_table.setValueAt(txtpatientname.getText(),row,1);
            patient_table.setValueAt(txtdob.getText(),row,2);
            patient_table.setValueAt(txtaddress.getText(),row,3);
            patient_table.setValueAt(txtmajordisease.getText(),row,5);
            patient_table.setValueAt(txtother.getText(),row,6);
        }else{
            JOptionPane.showMessageDialog(this,"Select a row");
        }
        try{
            MyDbConnection mycon=new MyDbConnection();
            Statement st=mycon.getMyConnection().createStatement();
            if(jTable1.getSelectedRowCount()==1){
                st.executeUpdate("Update patient set pname='"+txtpatientname.getText()+"',pDOB='"+txtdob.getText()+"',address='"+txtaddress.getText()+"',major_disease='"+txtmajordisease.getText()+"',other='"+txtother.getText()+"' where pid='"+txtpatientid.getText()+"'");
                JOptionPane.showMessageDialog(this,"Update successful");
                
            }else{
                JOptionPane.showMessageDialog(this,"Select one row only");
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
          
    }//GEN-LAST:event_btnupdateActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel patient_table=(DefaultTableModel)jTable1.getModel();
        int row=jTable1.getSelectedRow();
        txtpatientid.setText(patient_table.getValueAt(row,0).toString());
        txtpatientname.setText(patient_table.getValueAt(row,1).toString());
        txtdob.setText(patient_table.getValueAt(row,2).toString());
        txtaddress.setText(patient_table.getValueAt(row,3).toString());
        txtmajordisease.setText(patient_table.getValueAt(row,5).toString());
        txtother.setText(patient_table.getValueAt(row,6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddmedicine;
    private javax.swing.JButton btnaddpatient;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnpatientdelete;
    private javax.swing.JButton btnprescribe;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnshowpatients;
    private javax.swing.JButton btnshowprescription;
    private javax.swing.JButton btnupdate;
    private javax.swing.JCheckBox cbafternoon;
    private javax.swing.JCheckBox cbmorning;
    private javax.swing.JCheckBox cbnight;
    private javax.swing.JComboBox<String> cmbgender;
    private javax.swing.JComboBox<String> cmbmeal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel jpaddmedicine;
    private javax.swing.JPanel jpdochome;
    private javax.swing.JPanel jppatient;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtmajordisease;
    private javax.swing.JTextField txtother;
    private javax.swing.JTextField txtpatient;
    private javax.swing.JTextField txtpatientid;
    private javax.swing.JTextField txtpatientmed;
    private javax.swing.JTextField txtpatientname;
    private javax.swing.JTextField txtquantity;
    // End of variables declaration//GEN-END:variables
}
