/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnpatientlogin = new javax.swing.JButton();
        btndoctorlogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("Login");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 300, 80));

        btnpatientlogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnpatientlogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Desktop\\java project\\People-Patient-Male-icon.png")); // NOI18N
        btnpatientlogin.setText("Patient Login");
        btnpatientlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpatientloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnpatientlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 215, 267, 85));

        btndoctorlogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btndoctorlogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Desktop\\java project\\People-Patient-Male-icon (1).png")); // NOI18N
        btndoctorlogin.setText("Doctor Login");
        btndoctorlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoctorloginActionPerformed(evt);
            }
        });
        getContentPane().add(btndoctorlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 215, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Desktop\\java project\\1.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpatientloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpatientloginActionPerformed
        //To set PatientLogin frame visible when button clicked
        PatientLogin pl=new PatientLogin();
        pl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnpatientloginActionPerformed

    private void btndoctorloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoctorloginActionPerformed
        // To set DoctorLogin frame visible when button clicked
        DoctorLogin dl=new DoctorLogin();
        dl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btndoctorloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndoctorlogin;
    private javax.swing.JButton btnpatientlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
