
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
import java.sql.*; //import the package
import javax.swing.*;
import javax.swing.table.DefaultTableModel; //Contains the methods of JTables
public class Medicine extends javax.swing.JFrame {

    /**
     * Creates new form Medicine
     */
    public Medicine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btndelete = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnaddmedicine = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtmedname = new javax.swing.JTextField();
        txtmedcode = new javax.swing.JTextField();
        btnshowmedicine = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnaddmedicine1 = new javax.swing.JButton();

        setTitle("Medicine");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btndelete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 180, 40));

        btnrefresh.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 200, 40));

        jLabel5.setText("10 digit code");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 100, 20));

        btnaddmedicine.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnaddmedicine.setText("Add Medicine");
        btnaddmedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddmedicineMouseClicked(evt);
            }
        });
        btnaddmedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddmedicineActionPerformed(evt);
            }
        });
        getContentPane().add(btnaddmedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 180, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("code (NDC)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Medicine");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 150, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 70, 30));
        getContentPane().add(txtmedname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 280, 40));

        txtmedcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmedcodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtmedcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 280, 40));

        btnshowmedicine.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnshowmedicine.setText("Show Medicine");
        btnshowmedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnshowmedicineMouseClicked(evt);
            }
        });
        getContentPane().add(btnshowmedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 200, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Desktop\\java project\\main-qimg-0b16e64092f09eb7a12ed2e6700573d7.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine code (NDC)", "Medicine Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 450, 430));

        btnaddmedicine1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnaddmedicine1.setText("Show Medicine");
        btnaddmedicine1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaddmedicine1MouseClicked(evt);
            }
        });
        getContentPane().add(btnaddmedicine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 200, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnshowmedicineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnshowmedicineMouseClicked
        // TODO add your handling code here:
        /*
        This button is used to get all the medicine details saved in medicine table in the database
        */
        try{
            MyDbConnection mycon=new MyDbConnection();
            Statement st=mycon.getMyConnection().createStatement();
            ResultSet rst=st.executeQuery("Select * from medicine"); //if data available in medicine table rst will be filled
            while(rst.next()) 
            {
                String mid=rst.getString("mid"); 
                String mname=rst.getString("mname");
                
                
                String medicine_data[]={mid,mname};             //array created using the data retrieved from the medicine table
                DefaultTableModel all_medicine_table=(DefaultTableModel)jTable1.getModel(); //An object is created in TableModel interface (it contains the methods the JTable will use 
                all_medicine_table.addRow(medicine_data); //addRow method is used to add data to a row in a jTable
                
            }
        }
        catch(Exception e){                         //specifically the SQLException which is a compiled time exception. So it is handle before compiling
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnshowmedicineMouseClicked

    private void btnaddmedicine1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddmedicine1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddmedicine1MouseClicked

    private void btnaddmedicineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaddmedicineMouseClicked
        // TODO add your handling code here:
        String medicine_name, medicine_code;
        medicine_code=txtmedcode.getText();
        medicine_name=txtmedname.getText();
        int count;
        boolean record=false;
        
        try{
            
            MyDbConnection mycon=new MyDbConnection();
            Statement st=mycon.getMyConnection().createStatement();
            if(medicine_code.isEmpty() || medicine_name.isEmpty()){         //validation to prevent empty records
                JOptionPane.showMessageDialog(this,"Insert required data");     
            }else{
                if(medicine_code.length()==10){                             //NDC is a 10 digit code
                    for(int i=0;i<10;i++){
                        if(medicine_code.charAt(i)>='0' && medicine_code.charAt(i)<='9'){
                        record=true;
                        }
                    }
                    if(record){
                        ResultSet rst=st.executeQuery("Select * from medicine where mid='"+medicine_code+"'");
                        if(rst.next()){
                            JOptionPane.showMessageDialog(this, "Warning: Duplicate medicine code");
                        }else{
                            count=st.executeUpdate("insert into medicine values('"+medicine_code+"','"+medicine_name+"')");     //once all validations done, insert the record into medicine table
                            if(count>0){
                                JOptionPane.showMessageDialog(this,"Record is submitted");
                            }
                            txtmedname.setText("");txtmedcode.setText("");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Invalid medicine code");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Invalid medicine code");
                }
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnaddmedicineMouseClicked

    private void btnaddmedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddmedicineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnaddmedicineActionPerformed

    private void txtmedcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmedcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmedcodeActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
        DefaultTableModel medicine_table=(DefaultTableModel)jTable1.getModel();
        int row_count=jTable1.getRowCount();                        
        System.out.println(row_count);
        for(int i=row_count-1;i>=0;i--){
           medicine_table.removeRow(i);                     //clears the current rows in the table
        }
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel medicine_table=(DefaultTableModel)jTable1.getModel();
        int row=jTable1.getSelectedRow();
        String cell1=jTable1.getValueAt(row,0).toString();
        try{
            MyDbConnection mycon=new MyDbConnection();
            Statement st=mycon.getMyConnection().createStatement();
            if(jTable1.getSelectedRowCount()==1){
                st.executeUpdate("Delete from medicine where mid='"+cell1+"'");             //deletes the record from the medicine table
                JOptionPane.showMessageDialog(this,"Delete successful");
                medicine_table.removeRow(row);
            }else{
                JOptionPane.showMessageDialog(this,"Select one row only");
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddmedicine;
    private javax.swing.JButton btnaddmedicine1;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnshowmedicine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtmedcode;
    private javax.swing.JTextField txtmedname;
    // End of variables declaration//GEN-END:variables
}
